[build]
  command = "npm ci && npx sass --style=compressed ./public/styles/style.scss ./public/styles/style.css && npm run webpack"
  publish = "public"
  functions = "functions"

[build.environment]
  NODE_VERSION = "10.11.0"
  NPM_VERSION = "6.4.1"

[dev]
  command = "npm run startDev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "functions"
