[build]
  command = "npm install && npm run css"
  publish = "public"
  functions = "functions"

[dev]
  command = "npm run startDev"
  port = 3000

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/server"
  status = 200

[functions]
  directory = "functions"
